### ISSUE TITLE
依存先`workspace:*`パッケージの絶対パスエイリアス`@/*`が解決できない問題に対処する

### ISSUE THREAD

**Issue by ReoHakase** [astronomy-club-at-nitic/nitic-astronomy#102]
[TypeScript "paths" in monorepo](https://github.com/vercel/turbo/discussions/620#top)

# 症状
依存先のパッケージがパスエイリアス`@/*`を使って`export`している場合、呼び出し元のパッケージ側でモジュール解決ができない
```tsx
// packages/model/index.ts
export type { Article, ArticleDetail } from '@/model/article.model';
export type { Member } from '@/model/member.model';
export type { Tag } from '@/model/tag.model';
export type { Image } from '@/model/image.model';
export type { Id } from '@/model/id.model';

export { ArticleSchema, ArticleDetailSchema } from '@/model/article.model';
export { MemberSchema } from '@/model/member.model';
export { TagSchema } from '@/model/tag.model';
export { ImageSchema } from '@/model/image.model';
export { IdSchema } from '@/model/id.model';
```

```tsx
// packages/cms/src/service/article/get-article-detail.service.ts
import type { ArticleDetail } from '@nitic-astronomy/model'; // ここで死ぬ
import { convertArticleDetail } from '@/converter/article.converter';
import { client } from '@/infra/client.factory';
import type { MicroCmsArticle } from '@/infra/microcms.type';
import { MicroCmsApiEndpoint } from '@/infra/microcms.type';
```

```
@nitic-astronomy/cms:test:     ../model/index.ts:7:52 - error TS2307: Cannot find module '@/model/article.model' or its corresponding type declarations.
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test:     7 export { ArticleSchema, ArticleDetailSchema } from '@/model/article.model';
@nitic-astronomy/cms:test:                                                          ~~~~~~~~~~~~~~~~~~~~~~~
```

# 対処法
## `.tsconfig.json`を修正する
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "@nitic-astronomy/tsconfig/tsconfig.node.json",
  "compilerOptions": {
    "baseUrl": "./",
    "composite": true,
    "declaration": true,
    "declarationDir": "./dist/types",
    "declarationMap": true,
    "ignoreDeprecations": "5.0",
    "lib": ["dom", "dom.iterable", "es2022"],
    "paths": {
      "@/*": ["./src/*", "../model/src/*"]
    },
    "rootDir": "./"
  },
  "include": ["**/*"],
  "exclude": ["**/node_modules/**/*", "*.js"]
}
```

```
pnpm turbo test --filter cms
• Packages in scope: @nitic-astronomy/cms
• Running test in 1 packages
• Remote caching disabled
@nitic-astronomy/cms:test: cache miss, executing 11292d7528012f2b
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test: > @nitic-astronomy/cms@0.1.0 test /Users/ReoHakase/repos/nitic-astronomy/packages/cms
@nitic-astronomy/cms:test: > jest --silent=false --verbose false --passWithNoTests
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test: FAIL src/service/tag/get-tag-detail.service.spec.ts
@nitic-astronomy/cms:test:   ● Test suite failed to run
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test:     Configuration error:
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test:     Could not locate module @/model/article.model mapped as:
@nitic-astronomy/cms:test:     /Users/ReoHakase/repos/nitic-astronomy/packages/cms/src/$1.
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test:     Please check your configuration for these entries:
@nitic-astronomy/cms:test:     {
@nitic-astronomy/cms:test:       "moduleNameMapper": {
@nitic-astronomy/cms:test:         "/^@\/(.*)$/": "/Users/ReoHakase/repos/nitic-astronomy/packages/cms/src/$1"
@nitic-astronomy/cms:test:       },
@nitic-astronomy/cms:test:       "resolver": undefined
@nitic-astronomy/cms:test:     }
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test:        5 | export type { Id } from '@/model/id.model';
@nitic-astronomy/cms:test:        6 |
@nitic-astronomy/cms:test:     >  7 | export { ArticleSchema, ArticleDetailSchema } from '@/model/article.model';
@nitic-astronomy/cms:test:          | ^
@nitic-astronomy/cms:test:        8 | export { MemberSchema } from '@/model/member.model';
@nitic-astronomy/cms:test:        9 | export { TagSchema } from '@/model/tag.model';
@nitic-astronomy/cms:test:       10 | export { ImageSchema } from '@/model/image.model';
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test:       at createNoMappedModuleFoundError (../../node_modules/.pnpm/jest-resolve@29.5.0/node_modules/jest-resolve/build/resolver.js:759:17)
@nitic-astronomy/cms:test:       at Object.<anonymous> (../model/index.ts:7:1)
@nitic-astronomy/cms:test:       at Object.<anonymous> (src/service/tag/get-tag-detail.service.spec.ts:1:1)
@nitic-astronomy/cms:test:
@nitic-astronomy/cms:test: (node:70429) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added to [_0x1237cf]. Use emitter.setMaxListeners() to increase limit
@nitic-astronomy/cms:test: (Use `node --trace-warnings ...` to show where the warning was created)

...

@nitic-astronomy/cms:test: Test Suites: 7 failed, 7 total
@nitic-astronomy/cms:test: Tests:       0 total
@nitic-astronomy/cms:test: Snapshots:   0 total
@nitic-astronomy/cms:test: Time:        10.388 s
@nitic-astronomy/cms:test: Ran all test suites.
@nitic-astronomy/cms:test:  ELIFECYCLE  Test failed. See above for more details.
@nitic-astronomy/cms:test: ERROR: command finished with error: command (/Users/ReoHakase/repos/nitic-astronomy/packages/cms) pnpm run test exited (1)
command (/Users/ReoHakase/repos/nitic-astronomy/packages/cms) pnpm run test exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    13.278s

 ERROR  run failed: command  exited (1)
```

これだけじゃJestが動かない(おそらくNext(Webpack)でも動かない)
> For anyone working on CSR apps and use bundlers like webpack, vite, rollup, etc. make sure to configure them to understand the aliases.

> Important note on vite and rollup. They do not accept an array of paths for each alias, so we are forced to use a unique alias for each path. Namely, if I use "@/*": ["./src/*"] inside my packages/ui/tsconfig.json package and then have "@/*": ["./src/*", "../../packages/ui/src/*"] inside apps/web/tsconfig.json, typescript will be happy, but vite/rollup will not because we cannot setup aliases that accept an array of paths. Neither of the two options below work.

**Comment by dino3616** [comment]
自分もこれなってめんどくなって結局パスエイリアス使わないことにした記憶
タイトル見ただけだけど多分ここら辺？
- https://github.com/vercel/turbo/discussions/620

**Comment by ReoHakase** [comment]
> 自分もこれなってめんどくなって結局パスエイリアス使わないことにした記憶 タイトル見ただけだけど多分ここら辺？
> 
> * [TypeScript "paths" in monorepo vercel/turbo#620](https://github.com/vercel/turbo/discussions/620)

(一番上の行にそのリンク貼ってあるよ)

**Comment by ReoHakase** [comment]
まあこれが一番楽な解決方法かな
https://github.com/vercel/turbo/discussions/620#discussioncomment-4673458

**Comment by dino3616** [comment]
まぁ別に「最悪！！！！！くそ！！！」とかではないからいいんじゃないかとおもふ
